# Generated by Django 3.2.1 on 2021-07-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
