# Generated by Django 3.2.1 on 2021-07-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnxityTroubleParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('afraid_environment', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('shy', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('worry_much', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('being_crashed_manipulated', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
            ],
            options={
                'db_table': 'anxity_trouble_parent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BehaviorTroubleParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('insolent_wth_grown_ups', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('feels_attacked_defensive', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('descructive', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('deny_mistakes_blame_others', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('quarrelsome_get_involved_fight', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('bully_intimidate_comrades', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('constantly_fight', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('unhappy', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
            ],
            options={
                'db_table': 'behavoir_trouble_parent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraTroubleParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('chewing_mibbing_things', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('trouble_make_keep_friends', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('suck_chew_things', models.TextField()),
                ('dreamer', models.TextField(null=True)),
                ('lie_made_up_stories', models.TextField()),
                ('get_troubles_more_than_others', models.TextField()),
                ('speak_like_baby_stutters', models.TextField()),
                ('pout_sulk', models.TextField()),
                ('steal_things', models.TextField()),
                ('disobey_reluctantly_obey', models.TextField()),
                ('easily_wrinkled_easily_angry', models.TextField()),
                ('cannot_stop_during_repetitive_activity', models.TextField()),
                ('cruel', models.TextField()),
                ('break_rules', models.TextField()),
                ('not_get_along_with_brothers', models.TextField()),
                ('feeding_problems', models.TextField()),
                ('sleeping_problems', models.TextField()),
                ('feel_wronged_cry_out_injustice', models.TextField()),
                ('brags_boastful', models.TextField()),
                ('bowel_movement_problems', models.TextField()),
            ],
            options={
                'db_table': 'extra_trouble_parent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HyperActivityTroubleParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('excitable_impulsif', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('cry_often_easily', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('squirms', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('restless_needs_do_something', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('desctructive', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('not_complete_what_started', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('easily_distracted', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('moody', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('discouraged_when_effort_required', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('disrurb_other_children', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
            ],
            options={
                'db_table': 'hyperactivity_trouble_parent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImpulsivityTroubleParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('excitable_impulsif', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('control_everything', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('squirms', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('restless_needs_do_something', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
            ],
            options={
                'db_table': 'impulisivity_trouble_parent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningTroubleParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('has_learning_difficuties', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('not_complete_what_started', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('easily_disctracted', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('discouraged_when_effort_required', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
            ],
            options={
                'db_table': 'learning_trouble_parent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SomatisationTroubleParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('headaches', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('upset_stomach', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('physical_aches', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
                ('vomiting_nausea', models.TextField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('usual', 'usual'), ('always', 'always')])),
            ],
            options={
                'db_table': 'somatisation_trouble_parent',
                'abstract': False,
            },
        ),
    ]
