# Generated by Django 4.2 on 2023-04-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnxityTroubleParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afraid_new_things', models.TextField(db_column='afraid_new_things')),
                ('shy', models.TextField(db_column='shy')),
                ('worry_much', models.TextField(db_column='worry_much')),
                ('being_crashed_manipulated', models.TextField(db_column='being_crashed_manipulated')),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'anxiety_trouble_parent',
            },
        ),
        migrations.CreateModel(
            name='BehaviorTroubleParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insolent_with_grown_ups', models.TextField(db_column='insolent_wth_grown_ups')),
                ('feels_attacked_defensive', models.TextField(db_column='feels_attacked_defensive')),
                ('destructive', models.TextField(db_column='destructive')),
                ('deny_mistakes_blame_others', models.TextField(db_column='deny_mistakes_blame_others')),
                ('quarrelsome_get_involved_fight', models.TextField(db_column='quarrelsome_get_involved_fight')),
                ('bully_intimidate_comrades', models.TextField(db_column='bully_intimidate_comrades')),
                ('constantly_fight', models.TextField(db_column='constantly_fight')),
                ('unhappy', models.TextField(db_column='unhappy')),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'behaviour_trouble_parent',
            },
        ),
        migrations.CreateModel(
            name='FormAbrParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excitable_impulsive', models.TextField(db_column='excitable_impulsive')),
                ('cry_often_easily', models.TextField(db_column='cry_often_easily')),
                ('squirms', models.TextField(db_column='squirms')),
                ('restless_needs_do_something', models.TextField(db_column='restless_needs_do_something')),
                ('destructive', models.TextField(db_column='destructive')),
                ('trouble_finishing_things', models.TextField(db_column='trouble_finishing_things')),
                ('easily_being_distracted', models.TextField(db_column='easily_being_distracted')),
                ('moody', models.TextField(db_column='moody')),
                ('enability_finish_when_do_effort', models.TextField(db_column='enability_finish_when_do_effort')),
                ('disturb_other_children', models.TextField(db_column='disturb_other_children')),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'forme_abr_parent',
            },
        ),
        migrations.CreateModel(
            name='HyperActivityTroubleParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excitable_impulsive', models.TextField(db_column='excitable_impulsive')),
                ('want_dominate', models.TextField(db_column='want_dominate')),
                ('squirms', models.TextField(db_column='squirms')),
                ('restless_needs_do_something', models.TextField(db_column='restless_needs_do_something')),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'hyperactivity_trouble_parent',
            },
        ),
        migrations.CreateModel(
            name='LearningTroubleParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_learning_difficulties', models.TextField(db_column='has_learning_difficulties')),
                ('trouble_finishing_things', models.TextField(db_column='trouble_finishing_things')),
                ('easily_being_distracted', models.TextField(db_column='easily_being_distracted')),
                ('enability_finish_when_do_effort', models.TextField(db_column='enability_finish_when_do_effort')),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'learning_trouble_parent',
            },
        ),
        migrations.CreateModel(
            name='SomatisationTroubleParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headaches', models.TextField(db_column='headaches')),
                ('upset_stomach', models.TextField(db_column='upset_stomach')),
                ('physical_aches', models.TextField(db_column='physical_aches')),
                ('vomiting_nausea', models.TextField(db_column='vomiting_nausea')),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'somatisation_trouble_parent',
            },
        ),
    ]
