# Generated by Django 3.2.1 on 2021-07-22 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formparent', '0001_initial'),
        ('gestionpatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='somatisationtroubleparent',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='learningtroubleparent',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='impulsivitytroubleparent',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='hyperactivitytroubleparent',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='extratroubleparent',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='behaviortroubleparent',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='anxitytroubleparent',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
    ]
