# Generated by Django 4.2 on 2023-04-21 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionusers.doctor')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionusers.parent')),
            ],
            options={
                'db_table': 'consultations',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('birthdate', models.DateField()),
                ('gender', models.TextField(default='M')),
                ('sick', models.BooleanField(default=None, null=True)),
                ('score_parent', models.FloatField(default=0)),
                ('score_teacher', models.FloatField(default=0)),
                ('is_supervised', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionusers.parent')),
            ],
            options={
                'db_table': 'patients',
                'unique_together': {('parent', 'name', 'birthdate')},
            },
        ),
        migrations.CreateModel(
            name='Supervise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionusers.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient')),
            ],
            options={
                'db_table': 'supervises',
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField()),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient')),
            ],
            options={
                'db_table': 'diagnostics',
            },
        ),
    ]
