# Generated by Django 3.2.1 on 2021-07-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField()),
            ],
            options={
                'db_table': 'orientations',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.TextField()),
                ('parent_full_name', models.TextField()),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.TextField()),
                ('name', models.TextField(unique=True)),
                ('family_name', models.TextField()),
                ('birthdate', models.DateField()),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
