# Generated by Django 4.2 on 2023-04-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionusers', '0001_initial'),
        ('gestionpatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervise',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionusers.doctor'),
        ),
        migrations.AddField(
            model_name='supervise',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionusers.parent'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.consultation'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionusers.doctor'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionusers.parent'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('parent', 'name', 'birthdate')},
        ),
    ]
