# Generated by Django 3.2.1 on 2021-08-03 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionpatient', '0001_initial'),
        ('gestionusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionusers.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionusers.parent'),
        ),
        migrations.AddField(
            model_name='orientation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionusers.doctor'),
        ),
        migrations.AddField(
            model_name='orientation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('name', 'familyName')},
        ),
    ]
