# Generated by Django 3.2.1 on 2021-07-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorTroubleTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('arrogant_impolite', models.TextField()),
                ('angry_unexpected_behavior', models.TextField()),
                ('sensitive_criticism', models.TextField()),
                ('pout_sulk_easily', models.TextField()),
                ('moody', models.TextField()),
                ('brawler', models.TextField()),
                ('deny_mistakes_blame_others', models.TextField()),
            ],
            options={
                'db_table': 'behavoir_trouble_teacher',
            },
        ),
        migrations.CreateModel(
            name='ExtraTroubleTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('submissive_attitude_towards_authority', models.TextField()),
                ('less_accepted_by_group', models.TextField()),
                ('Trouble_integrating_with_other_students', models.TextField()),
                ('less_cooperate_with_classmates', models.TextField()),
            ],
            options={
                'db_table': 'extra_trouble_teacher',
            },
        ),
        migrations.CreateModel(
            name='HyperActivityTroubleTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('restless_squirms_chair', models.TextField()),
                ('distracted', models.TextField()),
                ('annoy_students', models.TextField()),
                ('pout_sulk_easily', models.TextField()),
                ('moody', models.TextField()),
                ('go_right_left', models.TextField()),
                ('easily_turn_on_impulsive', models.TextField()),
                ('Trouble_finishing_things', models.TextField()),
                ('upset_easily_make_effort', models.TextField()),
            ],
            options={
                'db_table': 'hyperactivity_trouble_teacher',
            },
        ),
        migrations.CreateModel(
            name='ImpulsivityTroubleTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('restless_squirms_chair', models.TextField()),
                ('unappropriate_noices', models.TextField()),
                ('immediately_satisfied_needs', models.TextField()),
                ('annoy_students', models.TextField()),
                ('go_right_left', models.TextField()),
                ('easily_turn_on_impulsive', models.TextField()),
                ('excessive_attention_from_teacher', models.TextField()),
            ],
            options={
                'db_table': 'impulsivity_trouble_teacher',
            },
        ),
        migrations.CreateModel(
            name='InattentionTroubleTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('distracted', models.TextField()),
                ('dreamer', models.TextField()),
                ('be_led_by_others', models.TextField()),
                ('Trouble_guiding_others', models.TextField()),
                ('Trouble_finishing_things', models.TextField()),
                ('immature', models.TextField()),
                ('easily_upset_make_effort', models.TextField()),
            ],
            options={
                'db_table': 'inattention_trouble_teacher',
            },
        ),
    ]
