# Generated by Django 3.2.1 on 2021-08-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionpatient', '0001_initial'),
        ('formteacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inattentiontroubleteacher',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='inattentiontroubleteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.teacher'),
        ),
        migrations.AddField(
            model_name='impulsivitytroubleteacher',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='impulsivitytroubleteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.teacher'),
        ),
        migrations.AddField(
            model_name='hyperactivitytroubleteacher',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='hyperactivitytroubleteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.teacher'),
        ),
        migrations.AddField(
            model_name='extratroubleteacher',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='extratroubleteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.teacher'),
        ),
        migrations.AddField(
            model_name='behaviortroubleteacher',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='behaviortroubleteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.teacher'),
        ),
    ]
