# Generated by Django 4.2 on 2023-04-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionpatient', '0001_initial'),
        ('formteacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inattentiontroubleteacher',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
    ]
