# Generated by Django 4.2 on 2023-04-20 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionpatient', '0001_initial'),
        ('gestionusers', '0001_initial'),
        ('formteacher', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inattentiontroubleteacher',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionusers.teacher'),
        ),
        migrations.AddField(
            model_name='hyperactivitytroubleteacher',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='hyperactivitytroubleteacher',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionusers.teacher'),
        ),
        migrations.AddField(
            model_name='formabrteacher',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='formabrteacher',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionusers.teacher'),
        ),
        migrations.AddField(
            model_name='behaviortroubleteacher',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionpatient.patient'),
        ),
        migrations.AddField(
            model_name='behaviortroubleteacher',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionusers.teacher'),
        ),
    ]
