# Generated by Django 4.2 on 2023-04-30 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formteacher', '0002_initial'),
        ('gestionusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formteacher',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionusers.personprofile'),
        ),
        migrations.AddField(
            model_name='formabrteacher',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formteacher.formteacher'),
        ),
        migrations.AddField(
            model_name='behaviortroubleteacher',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formteacher.formteacher'),
        ),
    ]
