# Generated by Django 4.2 on 2023-04-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formteacher', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formteacher',
            name='score',
        ),
        migrations.AddField(
            model_name='behaviortroubleteacher',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='formabrteacher',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hyperactivitytroubleteacher',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inattentiontroubleteacher',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
